print("Propocione los siguientes datos del libro: ")
nombreLibro = (input("Propociona el nombre: "))
idlibro = int(input("Propociona el ID: "))
precio = float(input("Propocina el precio: "))
indicacion = str(input("Indica si el envio es gratuito (Si/No)"))

print(nombreLibro)
print(idlibro)
print(precio)
print(indicacion)
